using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ColorSyncModel {
    [RealtimeProperty(1, true, true)]
    private Color _color;

    [RealtimeProperty(2, true, true)]
    private bool _isVisible;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ColorSyncModel : IModel {
    // Properties
    public UnityEngine.Color color {
        get { return _cache.LookForValueInCache(_color, entry => entry.colorSet, entry => entry.color); }
        set { if (value == color) return; _cache.UpdateLocalCache(entry => { entry.colorSet = true; entry.color = value; return entry; }); FireColorDidChange(value); }
    }
    public bool isVisible {
        get { return _cache.LookForValueInCache(_isVisible, entry => entry.isVisibleSet, entry => entry.isVisible); }
        set { if (value == isVisible) return; _cache.UpdateLocalCache(entry => { entry.isVisibleSet = true; entry.isVisible = value; return entry; }); FireIsVisibleDidChange(value); }
    }
    
    // Events
    public delegate void ColorDidChange(ColorSyncModel model, UnityEngine.Color value);
    public event         ColorDidChange colorDidChange;
    public delegate void IsVisibleDidChange(ColorSyncModel model, bool value);
    public event         IsVisibleDidChange isVisibleDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool              colorSet;
        public UnityEngine.Color color;
        public bool              isVisibleSet;
        public bool              isVisible;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public ColorSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireColorDidChange(UnityEngine.Color value) {
        try {
            if (colorDidChange != null)
                colorDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    public void FireIsVisibleDidChange(bool value) {
        try {
            if (isVisibleDidChange != null)
                isVisibleDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Color = 1,
        IsVisible = 2,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _color = color;
            _isVisible = isVisible;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IsVisible, _isVisible ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.colorSet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
                if (entry.isVisibleSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.IsVisible, entry.isVisible ? 1u : 0u);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(_color));
            stream.WriteVarint32((uint)PropertyID.IsVisible, _isVisible ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.colorSet || entry.isVisibleSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.colorSet)
                    stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(entry.color));
                if (entry.isVisibleSet)
                    stream.WriteVarint32((uint)PropertyID.IsVisible, entry.isVisible ? 1u : 0u);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool colorExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.colorSet);
        bool isVisibleExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.isVisibleSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Color: {
                    UnityEngine.Color previousValue = _color;
                    
                    _color = ReadStream.ColorFromBytes(stream.ReadBytes());
                    
                    if (!colorExistsInChangeCache && _color != previousValue)
                        FireColorDidChange(_color);
                    break;
                }
                case (uint)PropertyID.IsVisible: {
                    bool previousValue = _isVisible;
                    
                    _isVisible = (stream.ReadVarint32() != 0);
                    
                    if (!isVisibleExistsInChangeCache && _isVisible != previousValue)
                        FireIsVisibleDidChange(_isVisible);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
